sudo: false
language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install tox-travis pylintfileheader
script:
  - python -m pylint -j 0 -f parseable neptunelib tests
  - tox
